services:
  mage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mage
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      PYSPARK_SUBMIT_ARGS: "--packages org.postgresql:postgresql:42.6.0 pyspark-shell"
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - .:/home/src/
    ports:
      - "6789:6789"
   
networks:
  default:
    name: local-network
    external: false